// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8wRNqjTAAbI6REe52eEQp4v2yZrxEKI8',
    appId: '1:95669734352:web:239a212917b2c1e19407d5',
    messagingSenderId: '95669734352',
    projectId: 'sillywillyonweed',
    authDomain: 'sillywillyonweed.firebaseapp.com',
    storageBucket: 'sillywillyonweed.appspot.com',
    measurementId: 'G-RE4ZGJ8S1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJjK5vNf7zSdlm4ddk-SjZgmNLysW_qfI',
    appId: '1:95669734352:android:ae09096d8f6539399407d5',
    messagingSenderId: '95669734352',
    projectId: 'sillywillyonweed',
    storageBucket: 'sillywillyonweed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6UVtpYSQFSYpku2MBmj_ZmjQ8F908Rs',
    appId: '1:95669734352:ios:bfc2325a54a710b59407d5',
    messagingSenderId: '95669734352',
    projectId: 'sillywillyonweed',
    storageBucket: 'sillywillyonweed.appspot.com',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ6UVtpYSQFSYpku2MBmj_ZmjQ8F908Rs',
    appId: '1:95669734352:ios:56bde3e5ad8150929407d5',
    messagingSenderId: '95669734352',
    projectId: 'sillywillyonweed',
    storageBucket: 'sillywillyonweed.appspot.com',
    iosBundleId: 'com.example.nova.RunnerTests',
  );
}
